Fix some cops
theforeman/ldap_fluff pull request #74
Opened 2023-12-27 06:43 UTC by archanaserver

2024-01-03 06:57 UTC, archanaserver commented
@ekohl just raised this pr to update ruby version, this was way outdated https://github.com/theforeman/ldap_fluff/pull/75

2024-01-03 12:04 UTC, ekohl requested changes
The summary of this commit should be `Raise minimum Ruby version to 2.7`. Typically those kinds of changes are major version bumps.

2024-01-03 12:04 UTC, ekohl commented on Gemfile
> +gemspec :name => 'ldap_fluff'
Why is this needed?

2024-01-03 12:04 UTC, ekohl commented on Gemfile
> +gem 'theforeman-rubocop', github: 'archanaserver/theforeman-rubocop', branch: 'rubocop'
This shouldn't be in this PR.

2024-01-03 12:07 UTC, archanaserver commented
@ekohl ah i marked it as wip and so pushed random change to check the gha workflow result for the rubocop, because rake don't have rule to check rubocop result. do you want me to work on that first?

2024-01-03 12:16 UTC, ekohl commented
If it's WIP then using a draft PR makes it clear to reviewers.

2024-01-03 12:23 UTC, ekohl commented
> because rake don't have rule to check rubocop result. do you want me to work on that first?

You can also override the command provided to https://github.com/theforeman/actions/blob/v0/.github/workflows/rubocop.yml. We can also change the action. I recall @evgeni mentioning something similar because you can't enable parallel testing from Rakefile.

The reason I preferred the Rakefile approach in the action was that we very often had old versions of RuboCop that either didn't have the command line utility at all (that came later) or was too old to support `--parallel`.

By now I think we can start to enforce use of recent enough versions of RuboCop instead of keeping compatibility.

2024-01-09 07:11 UTC, archanaserver commented
This needs rebase once, #75 gets merged!

2024-01-18 12:30 UTC, ekohl commented
https://github.com/theforeman/ldap_fluff/pull/75 includes this and passed, so merging.

2024-01-18 12:30 UTC, merged

2024-01-19 17:55 UTC, archanaserver commented
> #75 includes this and passed, so merging.

Thank you @ekohl